# -*- coding: utf-8 -*-
"""session 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HExpffVMfED4XEoloLiktA1AqaqiiCJf
"""

x = 11
y = 12
x>y

x =20
y = 5
result = (x + True) / (4-y * False)
print(result)

g = 6.67 * 10**-11
M = 6.0 * 10**24
m = 7.34 * 10**22
r = 3.84 * 10**8
f = g*M*m/r**2
print(f)

x = float( input ("Enter your grad :"))
if x == 100:
    print("Ex")
elif x >= 90:
    print("V.G")
elif x >= 80 :
    print("Good")
else:
    print("LOSER")

list = [1,2,3,4,5,6]
list. append(10)
list

list.insert(0,10)
list

# to remove number from the list
list . pop(0)
list . pop(-1)
list . pop(1)
list

# to replace number in list
list[0] = 1
list

# to add number in the list
list. insert (-1, 7)
list

#list [start : end : step] defult[0:0:1]
list[::-1]

#to know the length of the list
len(list)

#to add list of numbers in the list
list. extend([[21,22,23]])
list

# to call number in list in list
list[-1][1]

list.remove(7)

# we use copy to can update in the new list without any change in the original list
list1 = list.copy()

list1

del(list1)

# take the numbers from the user and print
x1 = int( input("Enter the 1st number in the list: "))
x2 = int( input("Enter the 2ed number in the list: "))
x3 = int( input("Enter the 3rd number in the list: "))
x4 = int( input("Enter the 4st number in the list: "))
lst = []
lst.append(x1)
lst.append(x2)
lst.append(x3)
lst.append(x4)
lst

lst.count(2)

#split string
name = "Noure Mohamed Fawzy"
# to split every single name : name.split()
#make name in list to can split every single name
name = name.split()

#the split every single chart
list(name[0])

name

name[0][1].upper()

#list can contain multi types and can have updates
lst1= [1,2.3,"Noure"]

#Tuples: you cannot modify in item
# can have different data type: t = Tuple(1,2.3,'N')
# to changinr a tuple convert it to list
# join 2 tuple together : t1+t2 = t3
# multiply tuple: t*2
# tuple must have >1 element: t=(1,..)
t = (1,2,3,4)
type(t)

t.count(4)

lst = [1,2,3,4,5,5,5]
t = tuple(lst)
t

t.count(5)

t.index(2)

# to add number in tuple
t + (4,)

#Set{}: can obtain diffrents data types
# can use add() , remove(), in ,  update(), extend()
s = {1,2,3,3,4}
s

A = {1,2,3}
B = {3,4,5}
u= A.union (B)

i = A.intersection(B)
i

A.intersection_update(B)
A

# to check the elements in the set
1 in B

A.add(4)
A

# convert
lst = [1,2,3,4,5,5,5,7,3,2,6,7,7,8]
set(lst)

# delete the number from the set
lst.remove(5)
lst

'''
all can contain different data type
list [] ,index ,order ,changeable
tuple() ,index ,order ,unchangeable
set{} ,no index ,unorder bec set already sort the numbers ,changeable
dict{key: value,..} ,key ,order ,changeable
clear() copy()

'''

d = {"k1":"value",
     "k2":[1,2,3,[2,3,4,5,["A","B","ABCD"]]]}
d["k2"][-1][-1]=d["k2"][-1][-1][-1][0:2]+ d["k2"][-1][-1][-1][-2].lower() + d["k2"][-1][-1][-1][-1]

