# -*- coding: utf-8 -*-
"""Session 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n2tRVKRcpvHISGsvpqZmJZxfCrDFcBl7
"""

d = {'k1':[1,2,{'k2':['this is tricky',{'ahmed':[1,2,['hello']]}]}]}

d["k1"][-1]["k2"][-1]["ahmed"][-1][0] = d["k1"][-1]["k2"][-1]["ahmed"][-1][0].upper()

d

lst = [1,2,3,4,5]
for i in lst:
    print(i)

for i in range(10):
    print(i)

for i in range(1,21):
    if i % 2 == 0 :
        print(i , " even")
    else:
        print(i , " odd")

lst1 = [1,2,3,4]
lst2 = []
for i in lst1 :
    lst2.append( i * 2 )
print(lst2)

i = 0
while i <= 10 :
    print(i)
    i += 1

lst = [1,2,3,4,5,6]
for i in lst :
    if i == 3 :
        continue
    print(i)

lst = [1,2,3,4,5,6]
for i in lst :
    if i == 3 :
        break
    print(i)

lst = [1,2,3,4,5,6]
for i in lst :
    if i == 3 :
        pass
    print(i)

words = input("enter two words ")
words = words.split()
if words[0][0] == words[-1][0]:
    print(True)
else:
    print(False)

def add(n1 , n2 , n3 ):
    s = n1 + n2 + n3
    return s

add(10 , 10 , 10 )

def add_lst( l ):
    s = 0
    for i in l :
        s = s + i
    return s

add_lst(1,2,3,4,5,6,7,8)



num_input = int( input("enter num of values "))
lst = []
for i in range(num_input):
    lst.append(float(input("enter the number")))
print(lst)

add_lst(lst)

x = "G"
def say():
    global y
    y = "L"
    print(y)
    m = "local"
    def local_f():
#         nonlocal m
        m = "Nonlocal"
        print(m)
    local_f()
    print(m)
print(x)
say()
print(y)

s = "G"
def say():

    s = "local"
    print(s)
    def local_f():
#         nonlocal s
        s = "local_f"
        print("local_f ",s)
        def non():
            nonlocal s
            s = "non"
            print("non ",s)
        non()
        print(s)
    local_f()
    print(s)
print(s)
say()
print(s)

