# -*- coding: utf-8 -*-
"""Session 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rKWyvQaSs3IjomiRApwDzHWbtBu8Roso

# Session one
"""

# session one
print("ahmed ibrahim")

x = 5
type(x)

print("x")

print(x)

y = 5.5
type(y)

y = int(y)

print(y)

t = False
type(t)

x = 10
y = 20
s = x * y
print(s)

print(s)

x = 10
print(x)
print(id(x))

x = 20
print(x)
print(id(x))

name = "Amit learning"
print("name = ", name)

name = "sayed"
age = 30
print("my name is " , name , " and my age is " , age)

name = "sayed"
age = 30
print("my name is {} and my age is {}".format(name , age))

name = "sayed"
age = 30
print(f"my name is {name} and my age is {age}")

x = "amit learning"
x[-1]

x = "amit learning"
x = x[0].upper() + x[1::]

x

x[::-1]

x = int(input("enter the number "))

type(x)

