# -*- coding: utf-8 -*-
"""Session 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LhCzxNxAV4riMeMGuHcXGFQWHZq7JGDB
"""

def Remove(sets):
	sets.discard(20)
	return sets

# Driver Code
sets = set([10, 20, 26, 41, 54, 20])
Remove(sets)

sets

print(sets)

sets

###########session 4 :

x = str(input ("Enter string : "))
def inv(y):
    invy = y[::-1]
    print("the inverse is : ",invy)
    if y == invy:
        print("T")
inv(x)

def maxy(l):
    le = []
    for i in l:
        le.append(len(i))

    print(le)
    print(l[le.index(max(le))])


x =  int (input("how many strings you will enter : "))
lst = []
for i in range(x):
    l =  str (input(" enter the strings : "))
    lst.append(l)

#print(max(lst))
#print(min(lst))
maxy(lst)

word = "AMIT&-Learning!"
def checky(w):
    s =""
    illegal_chars = "0123456789!@#$%^&*()-+=[]{}|\\;:'\",.<>/?`~ "
    for i in w:
        if i in illegal_chars:
            s += ""
        else:
            s +=i
    print (s)
checky(word)

t = (1,2,3,4)
try:
    t.index(5)
except:
    # except = if
    print("not found")
else:
    #if try true, else will be true
    print("t")

t = (1,2,3,4)
try:
    print(t.index(1))
except:
    # except = if
    print("not found")
else:
    #if try true, else will be true
    print("t")

t = (1,2,3,4)
try:
    print(t.index(7))
except:
    # except = if the action you do if try = error
    print("not found")
else:
    #if try true, else will be true
    print("t")
finally:
    #finally will run everytime
    print("good")

#def add(n1, n2):
#    return n1 + n2

add = lambda n1, n2: n1 + n2

add(10, 20)

#filter (function: lambda , seq)
my_list = [1,2,3,4,5,6,7,8,9,10]
new = list(filter (lambda x: (x%2 == 0), my_list))
print (new)

lst = [1,2,3,4]
#بيمشي بالعكس هيبدا ب for loop
[i**i for i in lst]

lst = [[1,2,3],[4,5,6],[7,8,9]]
for i in lst:
    for j in i:
        print (j)

order = lambda x, function1: x + function1(x)
print(order(2, lambda x: x*x))

f = open ("text.txt", 'w')

f.write ("My name is Noure Mohamed Fawzy and my age is 22y")

f. close()

f = open ("text.txt", "r")
f.read()

# to open and creat a new file
f = open ("text2.txt", "a")

f.write ("that is a new file men no3 text created by useing \"a\" comman  ")

f. close()

f = open ("text2.txt", 'r')
f.read()

#a بيكمل علي بقيت الكتابه القديمه
#w بيمسح و بيعمل من اول وجديد

f = open("task.txt","w")

with open ("task.txt","w", encoding = "utf-8") as f:
    f.write ("Q1: Write a Python program to read a file line by line and store it into alist\n")
    f.write ("Q2: line 2\n")
    f.write ("Q3: line 3\n")
    f.write ("Q4:line 4\n")
    f.close()

with open ("task.txt","r", encoding = "utf-8") as f:
        lst =f.readlines()
        for i in range(len(lst)):
            lst[i]=lst[i].strip()
        print (lst)

x = "nour \n"
x

# remove space in the end or in the start and remove \n , \t
x.strip()

import test

test.add(1,2,3)

test.multp(1,2,3)

# shortcut test to t
import test as t
# * refer to all functions "the whole code" from the test without recall test
from test import *

import random as rd
# return all function in the module
dir(nd)

help (rd.random)

rd.random()

# [i,j>i] for randam number
rd.randint(1,10)

# [i, j>i[ for randam number

rd.randrange(1,10)

rd.choice(["Noure", "mohamed", "fawzy"])

lst = [1,2,3,4,5,6,7,8,9]
rd.shuffle(lst)
lst

import test1
test1.sub(1,2)

def f(x):
    if x == 1:
        return 1
    else:
        return x * f(x-1)
f(3)

"""### Ask the user to enter a command "add","sub","mult","div" and two  numbers to simulate a calculator. All of your functions are in a separate script calc.py Your main code is in main.py

"""

import Calculator as calc

calc.add(1,2)

calc.sub(3,2)

"""## Bonus: ask the user if he would like to make another operation or not. if yes, do it all over again in the same run. only exit the program if he says 'stop"""

# -------> TASK SESSION
def calcu():
    x = str (input ("What is the operation you want to make \"sum, sub, mult, div\" : "))
    n1 = float (input ("frist Number : "))
    n2 = float (input ("second Number : "))
    if x == "sum":
        print( calc.add(n1, n2))
    elif x == "sub":
        print (calc.sub(n1, n2))
    elif x == "mult":
        print (calc.mult(n1, n2))
    elif x == "div":
        print (calc.div(n1, n2))

ask = True
def again():
    while ask:
        y = str (input ("would like to make another operation \"yes or stop\" : "))
        if y == "stop":
            break
        else:
            calcu()
again()

